# Generated by Django 4.2.11 on 2025-05-06 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='职位标题')),
                ('company_logo', models.CharField(max_length=100, verbose_name='公司图片')),
                ('salary', models.CharField(max_length=50, verbose_name='薪资范围')),
                ('location', models.CharField(max_length=200, verbose_name='工作地点')),
                ('description', models.TextField(verbose_name='工作描述')),
                ('urgent', models.BooleanField(default=False, verbose_name='紧急')),
                ('distance', models.CharField(max_length=100, verbose_name='距离')),
                ('work_time', models.CharField(max_length=100, verbose_name='工作时间')),
                ('flash', models.BooleanField(default=False, verbose_name='闪电结')),
                ('work_type', models.CharField(max_length=10, verbose_name='工作类型')),
                ('work_require', models.CharField(max_length=100, verbose_name='工作要求')),
                ('education', models.CharField(max_length=100, verbose_name='学历')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='公司名称')),
            ],
        ),
    ]
