# Generated by Django 4.2.11 on 2025-05-06 12:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='服务评分')),
                ('comment', models.TextField(max_length=500, verbose_name='评价内容')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='匿名评价')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.serviceorder', verbose_name='关联订单')),
            ],
        ),
    ]
