# Generated by Django 4.2.11 on 2025-05-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='服务开始时间')),
                ('end_time', models.DateTimeField(verbose_name='服务结束时间')),
                ('payment_status', models.SmallIntegerField(choices=[(0, '待支付'), (1, '已支付'), (2, '退款中')], default=0, verbose_name='支付状态')),
            ],
        ),
    ]
