# Generated by Django 4.2.11 on 2025-05-06 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('job', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employer_orders', to='user.userprofile', verbose_name='雇主'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.jobpost', verbose_name='关联职位'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_orders', to='user.userprofile', verbose_name='接单人员'),
        ),
    ]
